services:
  api:
    image: langgenius/dify-api:latest ## Versão do Dify
    volumes:
      - storage_data:/app/api/storage
    networks:
      - network_public
    environment:
      - MODE=api
      - LOG_LEVEL=INFO
      - SECRET_KEY=sk-9f73s3ljTXVcMT3Blb3ljTqtsKiGHXVcMT3BlbkFJLK7U
      - CONSOLE_WEB_URL=
      - INIT_PASSWORD=Intruso99@
      - CONSOLE_API_URL=https://console.fluxosmm.com
      - SERVICE_API_URL=
      - FILES_URL=
      ## Url Dify
      - APP_WEB_URL=https://dify.fluxosmm.com
      ## Dados Postgres
      - MIGRATION_ENABLED=true
      - DB_USERNAME=cm336f5vq040ja7p769zwa0h5
      - DB_PASSWORD=q8NTtF1KpxXX5On9QXwLt8qu
      - DB_HOST=144.126.151.220
      - DB_PORT=9004
      - DB_DATABASE=cm336f5vr040la7p7dabebn9q
      ## Dados Redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_USERNAME=
      - REDIS_PASSWORD=q8NTtF1KpxXX5On9QXwLt8qu
      - REDIS_USE_SSL=false
      - REDIS_DB=0
      - CELERY_BROKER_URL=redis://:q8NTtF1KpxXX5On9QXwLt8qu@redis:6379/1
      ## Liberar acesso a todos os IPs
      - WEB_API_CORS_ALLOW_ORIGINS=*
      - CONSOLE_CORS_ALLOW_ORIGINS=*
      ## Dados sobre armazenamento s3
      - STORAGE_TYPE=local
      - STORAGE_LOCAL_PATH=storage
      - S3_ENDPOINT=db.fluxosmm.com
      - S3_BUCKET_NAME=difyai
      - S3_ACCESS_KEY=OqCEOydCqDaVJ2eXw8TQ
      - S3_SECRET_KEY=ViK4TTnGK05LbY2kmbXLmwuW3uYeqtwvMEC9inFh
      ## Dados Weaviate
      - VECTOR_STORE=weaviate
      - WEAVIATE_ENDPOINT=http://weaviate:8080
      - WEAVIATE_API_KEY=WVF5YThaHlkYwhGUSmCRgsX3tD5ngdN8pkih
      - WEAVIATE_CLIENT_TIMEOUT=20
      ## Dados do Email
      - MAIL_TYPE=smtp
      - MAIL_DEFAULT_SEND_FROM=contato@fluxosmm.com
      - SMTP_SERVER=smtp.hostinger.com
      - SMTP_PORT=465
      - SMTP_USERNAME=contato@fluxosmm.com
      - SMTP_PASSWORD=Intruso99@
      ## Sentry
      - SENTRY_DSN=
      - SENTRY_TRACES_SAMPLE_RATE=1.0
      - SENTRY_PROFILES_SAMPLE_RATE=1.0

    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M

  worker:
    image: langgenius/dify-api:latest ## Versão do Dify
    volumes:
      - storage_data:/app/api/storage
    networks:
      - network_public
    environment:
      - MODE=worker
      - LOG_LEVEL=INFO
      - SECRET_KEY=7017ebcb78fa10e5
      ## Dados Postgres
      - DB_USERNAME=cm336f5vq040ja7p769zwa0h5
      - DB_PASSWORD=q8NTtF1KpxXX5On9QXwLt8qu
      - DB_HOST=144.126.151.220
      - DB_PORT=9004
      - DB_DATABASE=cm336f5vr040la7p7dabebn9q
      ## Dados Redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_USERNAME=
      - REDIS_PASSWORD=q8NTtF1KpxXX5On9QXwLt8qu
      - REDIS_USE_SSL=false
      - REDIS_DB=0
      - CELERY_BROKER_URL=redis://:q8NTtF1KpxXX5On9QXwLt8qu@redis:6379/1
      ## Dados Weaviate
      - STORAGE_TYPE=local
      - STORAGE_LOCAL_PATH=storage
      - VECTOR_STORE=weaviate
      - WEAVIATE_ENDPOINT=http://weaviate:8080
      - WEAVIATE_API_KEY=WVF5YThaHlkYwhGUSmCRgsX3tD5ngdN8pkih
      - WEAVIATE_CLIENT_TIMEOUT=20
      ## Dados do Email
      - MAIL_TYPE=smtp
      - MAIL_DEFAULT_SEND_FROM=contato@fluxosmm.com
      - SMTP_SERVER=smtp.hostinger.com
      - SMTP_PORT=465
      - SMTP_USERNAME=contato@fluxosmm.com
      - SMTP_PASSWORD=Intruso99@

    depends_on:
      - postgres
      - redis          
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager       
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M

  web:
    image: langgenius/dify-web:latest ## Versão do Dify
    networks:
      - network_public
    environment:
      - EDITION=SELF_HOSTED
      - CONSOLE_API_URL=
      ## Url Dify
      - APP_API_URL=https://seudominio.com.br
      - SENTRY_DSN=
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M

  weaviate:
    image: semitechnologies/weaviate:1.19.0
    volumes:
      - weaviate_data:/var/lib/weaviate
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'false'
      PERSISTENCE_DATA_PATH: /var/lib/weaviate
      DEFAULT_VECTORIZER_MODULE: none
      CLUSTER_HOSTNAME: node1
      AUTHENTICATION_APIKEY_ENABLED: 'true'
      AUTHENTICATION_APIKEY_ALLOWED_KEYS: WVF5YThaHlkYwhGUSmCRgsX3tD5ngdN8pkih
      AUTHORIZATION_ADMINLIST_ENABLED: 'true'
      AUTHORIZATION_ADMINLIST_USERS: hello@dify.ai
    networks:
      - network_public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 2048M

volumes:
  storage_data:
    external: true
    name: storage_data
  weaviate_data:
    external: true
    name: weaviate_data

networks:
  network_public:
    external: true
    name: network_public
